-- Tango seed carte, generated from src/menuData.js by scripts/gen-seed.mjs.
-- Run AFTER schema.sql. Safe to re-run: existing rows are left untouched.

insert into categories (id, name, french, note, note_french, image_url, sort_order) values
  ('starters', 'Starters', 'Entrées', 'Served with house bread', 'Servi avec le pain maison', null, 0),
  ('salads', 'Salads', 'Salades', 'Large enough for a light main', 'Assez copieuses pour un plat léger', null, 1),
  ('grill', 'From the Grill', 'Grillades', 'Choose a side and a sauce', 'Au choix : un accompagnement et une sauce', null, 2),
  ('sea', 'From the Sea', 'Poissons et fruits de mer', null, null, null, 3),
  ('house', 'House Specialities', 'Spécialités de la maison', 'The dishes the kitchen is known for', 'Les plats qui font la maison', null, 4),
  ('pasta', 'Pasta & Risotto', 'Pâtes et risottos', null, null, null, 5),
  ('burgers', 'Burgers & Sandwiches', 'Burgers et sandwichs', 'All served with fries', 'Tous servis avec des frites', null, 6),
  ('sides', 'Sides', 'Accompagnements', null, null, null, 7),
  ('desserts', 'Desserts', 'Desserts', null, null, null, 8),
  ('drinks', 'Drinks', 'Boissons', null, null, null, 9)
on conflict (id) do nothing;

insert into dishes (id, category_id, name, french, price, image_url, hint, tags, available, sort_order) values
  ('st-1', 'starters', 'Beef Empanadas', 'Empanadas au bœuf · trois pièces', 4500, null, 'empanadas', '{pick}', true, 0),
  ('st-2', 'starters', 'Garlic Prawns', 'Crevettes à l’ail et persil', 7500, null, 'prawn pan', '{}', true, 1),
  ('st-3', 'starters', 'Grilled Provolone', 'Provolone grillé à l’origan', 5500, null, 'provoleta', '{veg}', true, 2),
  ('st-4', 'starters', 'Chicken Wings', 'Ailes de poulet marinées', 5000, null, 'wings', '{spicy}', true, 3),
  ('st-5', 'starters', 'Vegetable Spring Rolls', 'Nems aux légumes', 4000, null, 'spring rolls', '{veg}', true, 4),
  ('st-6', 'starters', 'Soup of the Moment', 'Soupe du moment', 3500, null, 'soup bowl', '{}', true, 5),
  ('sa-1', 'salads', 'Tango Caesar', 'César au poulet grillé', 7000, null, 'caesar', '{pick}', true, 0),
  ('sa-2', 'salads', 'Avocado & Grapefruit', 'Avocat et pamplemousse', 6500, null, 'avocado salad', '{veg}', true, 1),
  ('sa-3', 'salads', 'Grilled Goat Cheese', 'Salade de chèvre chaud', 7000, null, 'goat cheese', '{veg}', true, 2),
  ('sa-4', 'salads', 'Tuna Niçoise', 'Niçoise au thon', 7500, null, 'nicoise', '{}', true, 3),
  ('gr-1', 'grill', 'Rib Eye', 'Entrecôte 300 g', 16500, null, 'rib eye', '{pick}', true, 0),
  ('gr-2', 'grill', 'Beef Skewers', 'Brochettes de bœuf', 9500, null, 'skewers', '{}', true, 1),
  ('gr-3', 'grill', 'Half Chicken', 'Demi-poulet grillé', 8500, null, 'grilled chicken', '{}', true, 2),
  ('gr-4', 'grill', 'Lamb Chops', 'Côtelettes d’agneau', 15000, null, 'lamb chops', '{}', true, 3),
  ('gr-5', 'grill', 'Merguez Plate', 'Assiette de merguez', 8000, null, 'merguez', '{spicy}', true, 4),
  ('gr-6', 'grill', 'Mixed Grill for Two', 'Grillade mixte pour deux', 26000, null, 'mixed grill', '{pick}', true, 5),
  ('se-1', 'sea', 'Whole Grilled Sea Bream', 'Dorade entière grillée', 12000, null, 'sea bream', '{}', true, 0),
  ('se-2', 'sea', 'Captain Fillet', 'Filet de capitaine', 13500, null, 'captain fillet', '{pick}', true, 1),
  ('se-3', 'sea', 'Grilled Prawns', 'Gambas grillées', 15000, null, 'gambas', '{}', true, 2),
  ('se-4', 'sea', 'Fried Calamari', 'Calamars frits, sauce tartare', 9000, null, 'calamari', '{}', true, 3),
  ('ho-1', 'house', 'Braised Chicken & Attiéké', 'Poulet braisé et attiéké', 8500, null, 'poulet braise', '{pick}', true, 0),
  ('ho-2', 'house', 'Kedjenou', 'Kedjenou de poulet', 8000, null, 'kedjenou', '{spicy}', true, 1),
  ('ho-3', 'house', 'Peanut Stew', 'Sauce arachide, riz blanc', 7500, null, 'peanut stew', '{}', true, 2),
  ('ho-4', 'house', 'Garba Deluxe', 'Garba revisité', 6000, null, 'garba', '{new}', true, 3),
  ('pa-1', 'pasta', 'Beef Bolognese', 'Tagliatelles bolognaise', 7500, null, 'bolognese', '{}', true, 0),
  ('pa-2', 'pasta', 'Prawn Linguine', 'Linguine aux gambas', 10500, null, 'linguine', '{}', true, 1),
  ('pa-3', 'pasta', 'Mushroom Risotto', 'Risotto aux champignons', 8000, null, 'risotto', '{veg}', true, 2),
  ('pa-4', 'pasta', 'Four Cheese Penne', 'Penne aux quatre fromages', 7500, null, 'penne', '{veg}', true, 3),
  ('bu-1', 'burgers', 'Tango Burger', 'Burger maison, cheddar, oignons confits', 8000, null, 'burger', '{pick}', true, 0),
  ('bu-2', 'burgers', 'Chicken Club', 'Club sandwich au poulet', 6500, null, 'club sandwich', '{}', true, 1),
  ('bu-3', 'burgers', 'Veggie Burger', 'Burger végétarien', 6500, null, 'veggie burger', '{veg}', true, 2),
  ('si-1', 'sides', 'French Fries', 'Frites maison', 2500, null, 'fries', '{veg}', true, 0),
  ('si-2', 'sides', 'Attiéké', 'Attiéké', 2000, null, 'attieke', '{veg}', true, 1),
  ('si-3', 'sides', 'Fried Plantain', 'Alloco', 2500, null, 'alloco', '{veg}', true, 2),
  ('si-4', 'sides', 'Sautéed Vegetables', 'Légumes sautés', 3000, null, 'vegetables', '{veg}', true, 3),
  ('si-5', 'sides', 'White Rice', 'Riz blanc', 2000, null, 'rice', '{veg}', true, 4),
  ('de-1', 'desserts', 'Chocolate Fondant', 'Fondant au chocolat', 4500, null, 'fondant', '{pick}', true, 0),
  ('de-2', 'desserts', 'Crème Caramel', 'Crème caramel', 3500, null, 'creme caramel', '{}', true, 1),
  ('de-3', 'desserts', 'Seasonal Fruit', 'Assiette de fruits frais', 4000, null, 'fruit plate', '{veg}', true, 2),
  ('de-4', 'desserts', 'Ice Cream, Three Scoops', 'Glace, trois boules', 3500, null, 'ice cream', '{}', true, 3),
  ('dr-1', 'drinks', 'Bissap', 'Jus de bissap', 2000, null, 'bissap', '{veg}', true, 0),
  ('dr-2', 'drinks', 'Ginger Juice', 'Jus de gingembre', 2000, null, 'ginger juice', '{spicy}', true, 1),
  ('dr-3', 'drinks', 'Fresh Lemonade', 'Citronnade fraîche', 2500, null, 'lemonade', '{veg}', true, 2),
  ('dr-4', 'drinks', 'Still Water', 'Eau plate 1 L', 1000, null, 'water', '{}', true, 3),
  ('dr-5', 'drinks', 'Soft Drink', 'Soda au choix', 1500, null, 'soda', '{}', true, 4),
  ('dr-6', 'drinks', 'Espresso', 'Café expresso', 1500, null, 'espresso', '{}', true, 5)
on conflict (id) do nothing;
